import React, { useState, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import { Search, Briefcase, Code, DollarSign, BookOpen, Compass, Download, Play, Award, Calendar, ArrowRight, UserCheck } from 'lucide-react';
import { jsPDF } from 'jspdf';
import './CompanyPrep.css';

const CompanyPrep = () => {
  const { token, API_URL } = useContext(AuthContext);
  const [searchQuery, setSearchQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [loadingText, setLoadingText] = useState('Consulting CareerPilot database...');
  const [prepData, setPrepData] = useState(null);
  const [error, setError] = useState('');
  const [showDetailsModal, setShowDetailsModal] = useState(false);

  const fetchPrepData = async (company) => {
    if (!company) return;
    setLoading(true);
    setLoadingText(`Consulting CareerPilot AI database for ${company}...`);
    setError('');
    
    const steps = [
      `Fetching interview pattern parameters for ${company}...`,
      `Retrieving most asked DSA topics...`,
      `Gathering typical system design focuses...`,
      `Structuring standard HR behavior queries...`,
      `Checking salary & compensation estimates...`
    ];
    let idx = 0;
    const timer = setInterval(() => {
      setLoadingText(steps[idx]);
      idx = (idx + 1) % steps.length;
    }, 1200);

    try {
      const res = await fetch(`${API_URL}/career/prep`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({ companyName: company })
      });
      const data = await res.json();
      if (data.success) {
        setPrepData(data.data);
      } else {
        setError(data.message || 'Failed to fetch preparation guide.');
      }
    } catch (err) {
      setError('Connection timeout. Please try again.');
    } finally {
      clearInterval(timer);
      setLoading(false);
    }
  };

  const downloadMoreDetails = () => {
    if (!prepData || !prepData.moreDetailsText) return;
    const element = document.createElement("a");
    const file = new Blob([prepData.moreDetailsText], { type: 'text/plain;charset=utf-8' });
    element.href = URL.createObjectURL(file);
    element.download = `${prepData.companyName}_Detailed_Profile.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const downloadPDF = () => {
    if (!prepData) return;
    
    const doc = new jsPDF();
    let yPos = 20;

    // Title Section
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(30, 41, 59); // Slate 800
    doc.text(`${prepData.companyName} Preparation Roadmap`, 20, yPos);
    yPos += 12;

    // Subtitle / Date
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // Slate 500
    doc.text(`Generated by CareerPilot AI on ${new Date().toLocaleDateString()}`, 20, yPos);
    yPos += 15;

    // Compensation Info
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    doc.text("Estimated Annual Compensation (CTC):", 20, yPos);
    yPos += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105); // Slate 600
    doc.text(`- Fresher Package: ${prepData.salaryStats?.fresher || 'N/A'}`, 25, yPos);
    yPos += 6;
    doc.text(`- Experienced Package: ${prepData.salaryStats?.experienced || 'N/A'}`, 25, yPos);
    yPos += 15;

    // Interview Pattern Rounds
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Interview Rounds Breakdown", 20, yPos);
    yPos += 8;

    if (prepData.interviewRounds && Array.isArray(prepData.interviewRounds)) {
      prepData.interviewRounds.forEach((round, index) => {
        if (yPos > 260) {
          doc.addPage();
          yPos = 20;
        }

        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(79, 70, 229); // Indigo 600
        doc.text(`${index + 1}. ${round.roundName}`, 20, yPos);
        yPos += 6;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(9.5);
        doc.setTextColor(100, 116, 139);
        doc.text(`Focus: ${round.focus}`, 25, yPos);
        yPos += 6;

        // Topics list
        if (round.topics && round.topics.length > 0) {
          doc.setFont("helvetica", "bold");
          doc.setFontSize(9.5);
          doc.setTextColor(71, 85, 105);
          doc.text("Key Topics:", 25, yPos);
          
          const topicsText = round.topics.map(t => t.name).join(", ");
          doc.setFont("helvetica", "normal");
          doc.text(topicsText, 45, yPos);
          yPos += 6;
        }

        // Questions list
        if (round.questions && round.questions.length > 0) {
          doc.setFont("helvetica", "bold");
          doc.setFontSize(9.5);
          doc.setTextColor(71, 85, 105);
          doc.text("Recommended Questions:", 25, yPos);
          yPos += 6;

          round.questions.forEach(q => {
            if (yPos > 260) {
              doc.addPage();
              yPos = 20;
            }
            doc.setFont("helvetica", "normal");
            doc.setFontSize(9);
            doc.setTextColor(71, 85, 105);
            doc.text(`- [${q.difficulty}] ${q.title} (${q.platform})`, 30, yPos);
            yPos += 5;
          });
        }
        yPos += 5;
      });
    }

    // Weekly Roadmap
    if (yPos > 230) {
      doc.addPage();
      yPos = 20;
    } else {
      yPos += 5;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("10-Week Preparation Roadmap Plan", 20, yPos);
    yPos += 8;

    if (prepData.preparationRoadmap && Array.isArray(prepData.preparationRoadmap)) {
      prepData.preparationRoadmap.forEach((phase) => {
        if (yPos > 265) {
          doc.addPage();
          yPos = 20;
        }
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10.5);
        doc.setTextColor(6, 182, 212); // Cyan 600
        doc.text(phase.phase, 20, yPos);
        yPos += 6;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(9.5);
        doc.setTextColor(71, 85, 105);
        
        const textLines = doc.splitTextToSize(phase.milestone, 170);
        doc.text(textLines, 25, yPos);
        yPos += (textLines.length * 5) + 5;
      });
    }

    // Footer
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("This guide was customized based on real-time hiring trends. Prepare diligently!", 20, 285);

    doc.save(`${prepData.companyName}_Prep_Roadmap.pdf`);
  };

  const companiesList = [
    'TCS', 'Wipro', 'KPMG', 'Deloitte', 'Google', 'Microsoft', 'Amazon', 'Meta', 'Samsung', 'Accenture',
    'Flipkart', 'Zomato', 'Lenskart', 'Uber', 'Ola',
    'Meesho', 'Zepto', 'Razorpay', 'ShareChat', 'Paytm', 'Dunzo'
  ];

  const popularCompanies = [
    { name: 'TCS', color: 'rgba(0, 102, 204, 0.12)', border: '#0066cc', char: 'TCS' },
    { name: 'Wipro', color: 'rgba(90, 39, 142, 0.12)', border: '#5a278e', char: 'W' },
    { name: 'KPMG', color: 'rgba(0, 51, 153, 0.12)', border: '#003399', char: 'KPMG' },
    { name: 'Deloitte', color: 'rgba(134, 188, 37, 0.12)', border: '#86bc25', char: 'D' },
    { name: 'Google', color: 'rgba(219, 68, 85, 0.12)', border: '#db4437', char: 'G' },
    { name: 'Microsoft', color: 'rgba(0, 164, 239, 0.12)', border: '#00a4ef', char: 'M' },
    { name: 'Meta', color: 'rgba(6, 104, 226, 0.12)', border: '#0668e2', char: 'Meta' },
    { name: 'Uber', color: 'rgba(15, 15, 15, 0.4)', border: 'var(--text-primary)', char: 'U' },
    { name: 'Zomato', color: 'rgba(226, 55, 68, 0.12)', border: '#e23744', char: 'Z' }
  ];

  return (
    <div className="company-prep-view-details">
      <h1 className="page-title">Company Preparation Guides</h1>
      <p className="page-subtitle">Get detailed interview structures, top DSA concepts, system design topics, and salary stats for top tech companies.</p>

      {/* Popular Companies Grid */}
      <div className="popular-companies-cards-row" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(130px, 1fr))', gap: '0.85rem', marginBottom: '1.5rem' }}>
        {popularCompanies.map(item => {
          const isActive = searchQuery === item.name;
          return (
            <div 
              key={item.name}
              className={`popular-company-card ${isActive ? 'active' : ''}`}
              onClick={() => {
                setSearchQuery(item.name);
                fetchPrepData(item.name);
              }}
              style={{
                background: isActive ? 'var(--bg-item-hover)' : 'var(--bg-card)',
                border: `1px solid ${isActive ? item.border : 'var(--border-color)'}`,
                borderRadius: 'var(--radius-sm)',
                padding: '1rem',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                cursor: 'pointer',
                transition: 'var(--transition-smooth)',
                boxShadow: isActive ? `0 0 10px ${item.border}33` : 'none'
              }}
            >
              <div 
                style={{ 
                  width: '40px', 
                  height: '40px', 
                  borderRadius: '50%', 
                  background: item.color, 
                  border: `1px solid ${item.border}`, 
                  display: 'flex', 
                  alignItems: 'center', 
                  justifyContent: 'center', 
                  fontSize: '0.9rem', 
                  fontWeight: 800, 
                  color: item.border,
                  marginBottom: '0.5rem'
                }}
              >
                {item.char}
              </div>
              <span style={{ fontSize: '0.8rem', fontWeight: 700, color: 'var(--text-primary)' }}>{item.name}</span>
            </div>
          );
        })}
      </div>

      {/* Dropdown Selection Grid */}
      <div className="search-header-container glass-card" style={{ padding: '1.25rem 1.5rem' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', width: '100%' }}>
          <label htmlFor="company-dropdown-select" style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
            Or Select Other Company:
          </label>
          <div style={{ display: 'flex', gap: '1rem', width: '100%', flexWrap: 'wrap', alignItems: 'center' }}>
            <select
              id="company-dropdown-select"
              value={searchQuery}
              onChange={(e) => {
                const val = e.target.value;
                setSearchQuery(val);
                if (val) {
                  fetchPrepData(val);
                }
              }}
              style={{
                flex: 1,
                minWidth: '260px',
                padding: '0.75rem 1rem',
                borderRadius: 'var(--radius-sm)',
                background: 'var(--bg-item)',
                border: '1px solid var(--border-color)',
                color: 'var(--text-primary)',
                fontSize: '0.9rem',
                fontWeight: 600,
                outline: 'none',
                cursor: 'pointer',
                appearance: 'auto'
              }}
              disabled={loading}
            >
              <option value="">-- Choose Company --</option>
              {companiesList.map((name) => (
                <option key={name} value={name}>{name}</option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {error && (
        <div className="alert alert-error animate-fade-in" style={{ marginTop: '1rem', background: 'rgba(239, 68, 68, 0.1)', border: '1px solid var(--accent-error)', color: 'var(--accent-error)', padding: '0.85rem 1rem', borderRadius: 'var(--radius-sm)', fontSize: '0.85rem' }}>
          {error}
        </div>
      )}

      {loading && (
        <div className="prep-loader-wrapper glass-card animate-fade-in" style={{ marginTop: '1rem' }}>
          <div className="spinner-loader"></div>
          <p>{loadingText}</p>
        </div>
      )}

      {/* Main Analysis Display */}
      {prepData && !loading && (
        <div className="prep-report-grid animate-fade-in" style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          
          {/* Header Card (Salary Packages Comparison) */}
          <div className="prep-company-hero glass-card" style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', padding: '1.5rem 2rem', gap: '1.5rem' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '1.25rem' }}>
              <div className="hero-avatar-logo" style={{ fontSize: '1.8rem', fontWeight: 900 }}>
                {prepData.companyName.charAt(0).toUpperCase()}
              </div>
              <div>
                <h2 style={{ fontSize: '1.6rem', fontWeight: 800, margin: 0, color: 'var(--text-primary)' }}>{prepData.companyName}</h2>
                <p style={{ margin: '0.25rem 0 0', fontSize: '0.82rem', color: 'var(--text-muted)' }}>Verified Recruitment Syllabus Guide</p>
                {prepData.moreDetailsText && (
                  <button 
                    className="btn btn-secondary" 
                    onClick={() => setShowDetailsModal(true)}
                    style={{ marginTop: '0.5rem', fontSize: '0.75rem', padding: '0.25rem 0.6rem', minHeight: 'auto', display: 'flex', alignItems: 'center', gap: '0.25rem' }}
                  >
                    <BookOpen size={12} /> More Details
                  </button>
                )}
              </div>
            </div>

            {/* Side-by-side CTC comparison */}
            <div style={{ display: 'flex', gap: '1.5rem', flexWrap: 'wrap' }}>
              <div style={{ background: 'rgba(16, 185, 129, 0.08)', border: '1px solid rgba(16, 185, 129, 0.2)', padding: '0.75rem 1.25rem', borderRadius: 'var(--radius-sm)', minWidth: '160px' }}>
                <span style={{ fontSize: '0.72rem', textTransform: 'uppercase', color: '#10b981', fontWeight: 800, display: 'block', marginBottom: '0.2rem' }}>Fresher Salary Range</span>
                <span style={{ fontSize: '1.05rem', fontWeight: 800, color: 'var(--text-primary)' }}>{prepData.salaryStats?.fresher || 'Market Standard'}</span>
              </div>
              <div style={{ background: 'rgba(59, 130, 246, 0.08)', border: '1px solid rgba(59, 130, 246, 0.2)', padding: '0.75rem 1.25rem', borderRadius: 'var(--radius-sm)', minWidth: '180px' }}>
                <span style={{ fontSize: '0.72rem', textTransform: 'uppercase', color: '#3b82f6', fontWeight: 800, display: 'block', marginBottom: '0.2rem' }}>Experienced Salary (3+ Yrs)</span>
                <span style={{ fontSize: '1.05rem', fontWeight: 800, color: 'var(--text-primary)' }}>{prepData.salaryStats?.experienced || 'Market Standard'}</span>
              </div>
            </div>
          </div>

          {/* Timeline of Interview Rounds & Coding Practice */}
          <div className="glass-card" style={{ padding: '1.5rem 2rem' }}>
            <h3 style={{ fontSize: '1.15rem', fontWeight: 800, marginBottom: '1.5rem', borderBottom: '1px solid var(--border-color)', paddingBottom: '0.75rem', color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Briefcase size={18} style={{ color: 'var(--primary)' }} />
              Interview Rounds & Topic Checklist
            </h3>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
              {prepData.interviewRounds?.map((round, index) => (
                <div key={index} style={{ borderLeft: '3px solid var(--primary)', paddingLeft: '1.5rem', position: 'relative' }}>
                  {/* Round Index Bullet */}
                  <div style={{
                    position: 'absolute',
                    left: '-11px',
                    top: '2px',
                    width: '18px',
                    height: '18px',
                    borderRadius: '50%',
                    background: 'var(--bg-dark)',
                    border: '3px solid var(--primary)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center'
                  }}></div>

                  <h4 style={{ fontSize: '1.05rem', fontWeight: 800, color: 'var(--text-primary)', margin: '0 0 0.35rem 0' }}>{round.roundName}</h4>
                  <p style={{ margin: '0 0 1rem 0', fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Focus: {round.focus}</p>

                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem', flexWrap: 'wrap' }}>
                    {/* Key Topics & Learn Resources */}
                    <div>
                      <h5 style={{ fontSize: '0.75rem', textTransform: 'uppercase', color: 'var(--text-muted)', margin: '0 0 0.5rem 0', letterSpacing: '0.05em' }}>Key Topics & Reference Material</h5>
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                        {round.topics?.map((topic, i) => (
                          <div key={i} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'var(--bg-item)', padding: '0.5rem 0.75rem', borderRadius: '4px', border: '1px solid var(--border-color)' }}>
                            <span style={{ fontSize: '0.8rem', fontWeight: 700, color: 'var(--text-primary)' }}>{topic.name}</span>
                            <div style={{ display: 'flex', gap: '0.35rem' }}>
                              <a href={topic.articleUrl} target="_blank" rel="noopener noreferrer" className="btn btn-secondary" style={{ padding: '0.2rem 0.5rem', minHeight: 'auto', fontSize: '0.7rem', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                                <BookOpen size={12} /> Article
                              </a>
                              <a href={topic.youtubeUrl} target="_blank" rel="noopener noreferrer" className="btn btn-secondary" style={{ padding: '0.2rem 0.5rem', minHeight: 'auto', fontSize: '0.7rem', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                                <Play size={12} style={{ color: 'var(--accent-error)' }} /> Video
                              </a>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Actual LeetCode / Practice Questions */}
                    <div>
                      <h5 style={{ fontSize: '0.75rem', textTransform: 'uppercase', color: 'var(--text-muted)', margin: '0 0 0.5rem 0', letterSpacing: '0.05em' }}>Practice Questions (Direct links)</h5>
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                        {round.questions?.map((q, i) => {
                          let diffColor = 'var(--text-muted)';
                          if (q.difficulty === 'Easy') diffColor = '#10b981';
                          else if (q.difficulty === 'Medium') diffColor = '#f59e0b';
                          else if (q.difficulty === 'Hard') diffColor = '#ef4444';

                          return (
                            <a 
                              key={i} 
                              href={q.url} 
                              target="_blank" 
                              rel="noopener noreferrer" 
                              style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'var(--bg-item)', padding: '0.5rem 0.75rem', borderRadius: '4px', border: '1px solid var(--border-color)', textDecoration: 'none', transition: 'var(--transition-smooth)' }}
                              className="practice-question-row-link"
                            >
                              <span style={{ fontSize: '0.8rem', fontWeight: 700, color: 'var(--text-primary)' }}>{q.title}</span>
                              <span style={{ fontSize: '0.68rem', fontWeight: 800, padding: '0.15rem 0.4rem', borderRadius: '3px', border: `1px solid ${diffColor}`, color: diffColor }}>
                                {q.difficulty}
                              </span>
                            </a>
                          );
                        })}
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Interactive Preparation Roadmap Planner & Exporter */}
          <div className="glass-card" style={{ padding: '1.5rem 2rem' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border-color)', paddingBottom: '0.75rem', marginBottom: '1.25rem', gap: '1rem', flexWrap: 'wrap' }}>
              <h3 style={{ fontSize: '1.15rem', fontWeight: 800, margin: 0, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <Calendar size={18} style={{ color: 'var(--secondary)' }} />
                10-Week Structured Preparation Roadmap
              </h3>
              <button 
                className="btn btn-primary" 
                onClick={downloadPDF}
                style={{ fontSize: '0.82rem', padding: '0.5rem 1rem', minHeight: 'auto', display: 'flex', alignItems: 'center', gap: '0.35rem' }}
              >
                <Download size={14} /> Download Roadmap PDF
              </button>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              {prepData.preparationRoadmap?.map((phase, i) => (
                <div key={i} style={{ background: 'var(--bg-item)', border: '1px solid var(--border-color)', padding: '1.25rem', borderRadius: 'var(--radius-sm)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
                    <span style={{ fontSize: '0.72rem', fontWeight: 800, padding: '0.2rem 0.5rem', background: 'rgba(6, 182, 212, 0.1)', color: 'var(--secondary)', border: '1px solid rgba(6, 182, 212, 0.2)', borderRadius: '3px' }}>
                      PHASE {i + 1}
                    </span>
                    <h4 style={{ fontSize: '0.92rem', fontWeight: 800, color: 'var(--text-primary)', margin: 0 }}>{phase.phase}</h4>
                  </div>
                  <p style={{ margin: 0, fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: '1.5' }}>
                    {phase.milestone}
                  </p>
                </div>
              ))}
            </div>
          </div>

        </div>
      )}

      {/* Empty State */}
      {!prepData && !loading && (
        <div className="empty-results-prep glass-card">
          <Briefcase size={48} className="empty-prep-icon" style={{ opacity: 0.3, marginBottom: '1.5rem' }} />
          <h3>No Company Selected</h3>
          <p>Choose one of the popular tech companies above or use the dropdown to retrieve dynamic recruitment guides.</p>
        </div>
      )}

      {/* Details Modal */}
      {showDetailsModal && prepData && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          width: '100%',
          height: '100%',
          background: 'rgba(0, 0, 0, 0.65)',
          backdropFilter: 'blur(4px)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 9999,
          padding: '1rem'
        }}>
          <div className="glass-card" style={{
            width: '100%',
            maxWidth: '650px',
            background: 'var(--bg-card)',
            border: '1px solid var(--border-color)',
            borderRadius: 'var(--radius-md)',
            boxShadow: 'var(--shadow-lg)',
            display: 'flex',
            flexDirection: 'column',
            maxHeight: '85vh',
            animation: 'scaleUp 0.25s ease'
          }}>
            {/* Modal Header */}
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              padding: '1.25rem 1.5rem',
              borderBottom: '1px solid var(--border-color)'
            }}>
              <h3 style={{ margin: 0, fontSize: '1.2rem', fontWeight: 800, color: 'var(--text-primary)' }}>
                {prepData.companyName} Corporate Profile
              </h3>
              <button 
                onClick={() => setShowDetailsModal(false)}
                style={{
                  background: 'none',
                  border: 'none',
                  color: 'var(--text-muted)',
                  cursor: 'pointer',
                  fontSize: '1.2rem',
                  padding: '0.2rem'
                }}
              >
                &times;
              </button>
            </div>

            {/* Modal Body */}
            <div style={{
              padding: '1.5rem',
              overflowY: 'auto',
              flex: 1,
              fontSize: '0.88rem',
              color: 'var(--text-secondary)',
              lineHeight: '1.6',
              whiteSpace: 'pre-wrap'
            }}>
              {prepData.moreDetailsText}
            </div>

            {/* Modal Footer */}
            <div style={{
              display: 'flex',
              justifyContent: 'flex-end',
              gap: '1rem',
              padding: '1rem 1.5rem',
              borderTop: '1px solid var(--border-color)'
            }}>
              <button 
                className="btn btn-secondary" 
                onClick={() => setShowDetailsModal(false)}
                style={{ fontSize: '0.85rem' }}
              >
                Close
              </button>
              <button 
                className="btn btn-primary" 
                onClick={downloadMoreDetails}
                style={{ fontSize: '0.85rem' }}
              >
                Download Profile
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default CompanyPrep;
